In [1]:
import csv
from datetime import datetime
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
#create an url based on title and location
def get_url(position, location):
    """Generate url from position and location"""
    template = 'https://www.indeed.com/jobs?q={}&l={}'
    position = position.replace(' ', '+')
    location = location.replace(' ', '+')
    url = template.format(position, location)
    return url

In [3]:
#get full description of a Job (url)
def getFullDescription(url):
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')
    jobTitle = soup.find_all('div', class_='jobsearch-JobInfoHeader-title-container') 
    jobDscription = soup.find_all('div', class_='jobsearch-jobDescriptionText')
    result={}
    result['title']=jobTitle[0].text
    result['Description']=jobDscription[0].text
    return result

In [6]:
#url as an example
# get some JobOffers and store them into a dataframe
titles=[]
descriptions=[]
for p in range(2,12):
    url="https://uk.indeed.com/jobs?q=SALES&l=United%20Kingdom&start="+str((p*10))
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')
    frames=soup.find_all('div', 'mosaic-provider-jobcards')
    divcard=frames[0]
    for c in divcard.children:
        blockType=c.name
        if blockType=="a":
            link=c.get("href")
            urlJob="https://uk.indeed.com"+link
            results=getFullDescription(urlJob)
            titles.append(results['title'])
            descriptions.append(results['Description'])
            print (urlJob)
rows = {'Title': titles, 'Description': descriptions}
df = pd.DataFrame(data=rows)
df.to_csv("SALES.csv")

https://uk.indeed.com/rc/clk?jk=295dd432199a8abf&fccid=c08e3f14d662230d&vjs=3
https://uk.indeed.com/rc/clk?jk=202f7603f2fd4c05&fccid=af02b98b92a2145b&vjs=3
https://uk.indeed.com/rc/clk?jk=1a08d93a43ccc452&fccid=663ece44ae074b32&vjs=3
https://uk.indeed.com/rc/clk?jk=7a45d72d4bfe629c&fccid=0b8ac05c7cda03b4&vjs=3
https://uk.indeed.com/rc/clk?jk=8d2afb03e140052d&fccid=aaf3b433897ea465&vjs=3
https://uk.indeed.com/rc/clk?jk=b44f1cb5bb2fd5a6&fccid=4d45cd86e15de304&vjs=3
https://uk.indeed.com/rc/clk?jk=476766e315b5a2bb&fccid=160efb82f2462f14&vjs=3
https://uk.indeed.com/rc/clk?jk=68003434b13f48ab&fccid=1845b845b5c5b66e&vjs=3
https://uk.indeed.com/rc/clk?jk=5fc3047643885f4c&fccid=04c9b139c84ea1b5&vjs=3
https://uk.indeed.com/rc/clk?jk=a3b2cdc506d8b1c2&fccid=7de4ebb0eff0c7c2&vjs=3
https://uk.indeed.com/rc/clk?jk=29d19d869c0aa1be&fccid=25fcc0ef2edd3f05&vjs=3
https://uk.indeed.com/rc/clk?jk=d09a9a606b91f428&fccid=dde460449ad6f8d7&vjs=3
https://uk.indeed.com/rc/clk?jk=7ddce3f75d83d589&fccid=003656df63cede32&vjs=3
https://uk.indeed.com/rc/clk?jk=b7e161814b3f144b&fccid=9e215d88a6b33622&vjs=3
https://uk.indeed.com/rc/clk?jk=413de316381178d4&fccid=6ac73132d66f1daf&vjs=3

,Title,Description
0,Graduate Data Scientist,Graduate Data Scientist\nWe’re looking for Gra...
1,Principle Data Analytics Consultant,Principle Data Analytics Consultant Up to £155...
2,Analytics & Data Science Opportunities,What We'll Bring:\nAbout TransUnion\n\nAt Tran...
3,Data Scientist,As our Data Scientist you'll play a key role w...
4,Data Scientist - FX Services - Currencies & Em...,About the team\nFX Services is part of Currenc...
5,Data Science Internship,"Job Information\nStart date\nJune 6, 2022\nInd..."
6,"Data Scientist II, Analytics","Data Scientist II, Analytics\nAt Expedia Group..."
7,DATA SCIENTIST,Data Scientist – £550 Per Day Inside IR35 – Re...
8,Data Scientist,Role Title: Data Scientist\nBusiness: Complian...
9,R - Data Scientist Research Associate,We are seeking a Research Associate who will b...
10,Digital Marketing Data Scientist,Want to show the way in digital? As a Digital ...
11,Data Scientist - Ecommerce,“We are on a mission to transform the future o...
12,Real World Data Scientist,"Gothenburg, SWE, | Cambridge, UK | Gaithersbur..."
13,"Data Scientist, Deloitte Ventures, Tax, London",Basic information\nLocation\nLondon\nService l...
14,Process Data Scientist,The Opportunity\nJoin the Development Sciences...